// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zktgwklzcizpnqqvuilr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprdGd3a2x6Y2l6cG5xcXZ1aWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0Nzk5NDMsImV4cCI6MjA2NjA1NTk0M30.IAXP4ungm30MZ1_P-s2-38WCsMi4CXNBcx19eBpOCFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);